import { useEffect, useMemo, useState } from 'react';
import { getJson, postJson } from './api';
import DocumentsPanel from './components/DocumentsPanel';
import SummaryPanel from './components/SummaryPanel';
import ChatPanel from './components/ChatPanel';

//This defines the initial state of the chat as an array of message objects.
//Each message contains a role and text. I use this to pre-populate the UI
//with a bot instruction so the user understands how to interact with the system.
const DEFAULT_CHAT = [
  { role: 'bot', text: 'Upload documents. Once indexed, ask questions or compare documents using the RAG-powered assistant.' }
];

const SESSION_STORAGE_KEY = 'ragSessionId';

function formatSummaryText(answer = {}) {
  return answer.summary || answer.final_answer || answer.relevant_sections?.[0]?.section_summary || 'Insights generated.';
}

function formatImportantPoints(answer = {}) {
  const insights = Array.isArray(answer.key_insights) ? answer.key_insights : [];
  const sections = Array.isArray(answer.relevant_sections) ? answer.relevant_sections : [];

  const insightPoints = insights.map((insight, index) => {
    const title = insight.title || `Insight ${index + 1}`;
    const explanation = insight.explanation ? ` - ${insight.explanation}` : '';
    return `- ${title}${explanation}`;
  });

  if (insightPoints.length > 0) {
    return insightPoints;
  }

  const sectionPoints = sections.map((section, index) => {
    const sectionTitle = section.section_title || `Relevant section ${index + 1}`;
    const sectionSummary = section.section_summary ? ` - ${section.section_summary}` : '';
    return `- ${sectionTitle}${sectionSummary}`;
  });

  return sectionPoints.length > 0 ? sectionPoints : ['No critical points detected.'];
}

function readStoredSessionId() {
  try {
    return window.localStorage.getItem(SESSION_STORAGE_KEY) || '';
  } catch {
    return '';
  }
}

export default function App() {
  // --- STATE ---
  //I use the useState hook to manage the list of uploaded documents.
  //It’s initialized as an empty array, and I update it immutably using the setter function so React can trigger re-renders properly
  const [uploadedDocuments, setUploadedDocuments] = useState([]); // This is destructured into two parts: the state variable (uploadedDocuments) and the function to update it (setUploadedDocuments). I initialize it as an empty array since no documents are uploaded at the start. Whenever I want to update this list, I call setUploadedDocuments with a new array, which allows React to detect the change and re-render the UI accordingly.
  const [selectedFiles, setSelectedFiles] = useState([]);
  const [uploadStatus, setUploadStatus] = useState('No documents uploaded yet.');
  const [activeDocument, setActiveDocument] = useState('No document selected');
  const [analysisReady, setAnalysisReady] = useState(false);
  const [sessionId, setSessionId] = useState(() => readStoredSessionId());
  // {} is the initial state for documentSummaries, which will hold the summaries keyed by document name. 
  // NEW: Store the automatic summaries generated by the backend
  const [documentSummaries, setDocumentSummaries] = useState({});
  
  // Summary Panel State
  const [summary, setSummary] = useState('Upload documents to view the summary.');
  const [importantPoints, setImportantPoints] = useState([]);
  
  const [isUploading, setIsUploading] = useState(false);
  const [chatLog, setChatLog] = useState(DEFAULT_CHAT);
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('split');

  // --- INITIAL LOAD ---
  // just run once on component mount to check if we have any existing uploaded documents (in case of a refresh or returning user)
  useEffect(() => {
    const loadStatus = async () => {
      const storedSessionId = readStoredSessionId();
      if (!storedSessionId) {
        return;
      }

      try {
        const status = await getJson(`/api/status?session_id=${encodeURIComponent(storedSessionId)}`);
        setSessionId(status.sessionId || storedSessionId);
        const docs = status.uploadedDocuments || [];
        setUploadedDocuments(docs);
        setAnalysisReady(Boolean(status.analysisReady));
        setDocumentSummaries(status.summaries || {});
        if (docs.length > 0) {
          setActiveDocument(docs[0]);
        } else {
          setActiveDocument(null);
        }
      } catch (err) {
        console.error("Error fetching status:", err);
        // Keep defaults
      }
    };
    loadStatus();
  }, []);

  // --- AUTO-UPDATE SUMMARY PANEL ---
  // When the active document changes, update the summary
  useEffect(() => {
    if (!activeDocument) {
      setSummary('Select a document from the list to view its summary.');
      setImportantPoints([]);
      return;
    }
    
    if (documentSummaries[activeDocument]) {
      // Extract the JSON data we saved during upload
      const docData = documentSummaries[activeDocument].answer || {};

      setSummary(formatSummaryText(docData));
      setImportantPoints(formatImportantPoints(docData));
      
    } else {
      setSummary(analysisReady
        ? `No insights available for ${activeDocument}. Click Extract Insights to regenerate.`
        : 'Upload files and click Extract Insights to generate document insights.');
      setImportantPoints([]);
    }
  }, [activeDocument, documentSummaries, analysisReady]);

  const documentCountLabel = useMemo(() => {
    if (uploadedDocuments.length === 0) return 'No files loaded';
    if (uploadedDocuments.length === 1) return '1 file loaded';
    return `${uploadedDocuments.length} files loaded`;
  }, [uploadedDocuments]);

  // --- HANDLERS ---
  const handleUpload = async () => {
    if (selectedFiles.length === 0) {
      setUploadStatus('Choose one or more documents first.');
      return;
    }

    const formData = new FormData();
    selectedFiles.forEach((file) => formData.append('files', file));
    if (sessionId) {
      formData.append('session_id', sessionId);
    }

    setIsUploading(true);
    setUploadStatus('Uploading documents to active session...');

    try {
      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData
      });
      const data = await response.json();
      
      if (!response.ok) throw new Error(data.detail || 'Upload failed');

      setSessionId(data.session_id || '');
      if (data.session_id) {
        window.localStorage.setItem(SESSION_STORAGE_KEY, data.session_id);
      }
      const nextDocuments = data.uploadedDocuments || [];
      const nextActiveDocument = nextDocuments.includes(activeDocument) && activeDocument
        ? activeDocument
        : nextDocuments[0] || null;

      setUploadedDocuments(nextDocuments);
      setAnalysisReady(Boolean(data.analysisReady));
      setDocumentSummaries(data.summaries || {});
      setActiveDocument(nextActiveDocument);
      setUploadStatus(`${data.uploaded} document(s) uploaded. Click Extract Insights to index them.`);
      setSelectedFiles([]);
    } catch (error) {
      setUploadStatus(error.message);
    } finally {
      setIsUploading(false);
    }
  };

  const handleReset = async () => {
    try {
      if (sessionId) {
        await postJson('/api/reset', { session_id: sessionId });
      }
      window.localStorage.removeItem(SESSION_STORAGE_KEY);
      setSessionId('');
      setUploadedDocuments([]);
      setSelectedFiles([]);
      setDocumentSummaries({});
      setAnalysisReady(false);
      setUploadStatus('Workspace reset.');
      setActiveDocument(null);
      setQueryScope('single');
      setSummary('Upload documents to view the summary.');
      setImportantPoints([]);
      setChatLog(DEFAULT_CHAT);
    } catch (error) {
      setUploadStatus(error.message);
    }
  };

  const handleAnalyze = async () => {
    if (!sessionId) {
      setUploadStatus('Upload files first.');
      return;
    }

    if (uploadedDocuments.length === 0) {
      setUploadStatus('Upload documents first.');
      return;
    }

      setIsUploading(true);
    setUploadStatus('Running extraction and indexing on uploaded documents...');

    try {
      const data = await postJson('/api/analyze', { session_id: sessionId });
      setAnalysisReady(Boolean(data.analysisReady));
      if (data.sessionId) {
        setSessionId(data.sessionId);
        window.localStorage.setItem(SESSION_STORAGE_KEY, data.sessionId);
      }
      const nextDocuments = data.uploadedDocuments || uploadedDocuments;
      const nextActiveDocument = nextDocuments.includes(activeDocument) && activeDocument
        ? activeDocument
        : nextDocuments[0] || null;

      setDocumentSummaries(data.summaries || {});
      setUploadedDocuments(nextDocuments);
      setActiveDocument(nextActiveDocument);
      setUploadStatus('Extraction complete. Insights are available.');
    } catch (error) {
      setUploadStatus(error.message);
    } finally {
      setIsUploading(false);
    }
  };

  // Handles routing queries based on query scope or compare mode
  const handleSendMessage = async (message, isCompareMode, fileA, fileB) => {
    if (!message.trim()) return;

    const newChatLog = [...chatLog, { role: 'user', text: message }];
    setChatLog(newChatLog);
    setIsChatLoading(true);

    try {
      let responseData;

      if (isCompareMode) {
        // Compare mode - compares two specific documents
        const targetA = fileA || uploadedDocuments[0];
        const targetB = fileB || uploadedDocuments[1];
        if (!targetA || !targetB) {
          throw new Error("Comparison requires 2 selected documents.");
        }
        responseData = await postJson('/api/compare', { 
          session_id: sessionId,
          query: message,
          file_a: targetA,
          file_b: targetB
        });
      } else {
        // Single document mode
        if (!activeDocument) {
          throw new Error("Please select a document first.");
        }
        responseData = await postJson('/api/query', { 
          session_id: sessionId,
          query: message, 
          target_file: activeDocument 
        });
      }

      const aiAnswer = responseData.data?.answer || responseData.answer || { final_answer: "No response." };
      const sources = responseData.data?.sources || responseData.sources || [];
      setChatLog([...newChatLog, { role: 'bot', text: aiAnswer, sources: sources }]);

    } catch (error) {
      setChatLog([...newChatLog, { role: 'bot', text: error.message }]);
    } finally {
      setIsChatLoading(false);
    }
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <div className="logo-section">
          <h1>RAG Document Intelligence</h1>
          <span className="badge">Groq Workspace</span>
        </div>

        <div className="tab-navigation">
          <button 
            type="button" 
            className={`tab-btn ${activeTab === 'split' ? 'active' : ''}`}
            onClick={() => setActiveTab('split')}
          >
            Split View
          </button>
          <button 
            type="button" 
            className={`tab-btn ${activeTab === 'files' ? 'active' : ''}`}
            onClick={() => setActiveTab('files')}
          >
            Workspace Hub
          </button>
          <button 
            type="button" 
            className={`tab-btn ${activeTab === 'insights' ? 'active' : ''}`}
            onClick={() => setActiveTab('insights')}
          >
            Insights View
          </button>
          <button 
            type="button" 
            className={`tab-btn ${activeTab === 'chat' ? 'active' : ''}`}
            onClick={() => setActiveTab('chat')}
          >
            AI Assistant
          </button>
        </div>

        <div className="status-section">
          <span className="status-dot"></span>
          <span className="status-text">{uploadedDocuments.length} Active Files</span>
        </div>
      </header>

      <main className={`dashboard view-${activeTab}`}>
        <DocumentsPanel
          uploadedDocuments={uploadedDocuments}
          selectedFiles={selectedFiles}
          setSelectedFiles={setSelectedFiles}
          uploadStatus={uploadStatus}
          activeDocument={activeDocument}
          setActiveDocument={setActiveDocument}
          documentCountLabel={documentCountLabel}
          onUpload={handleUpload}
          onAnalyze={handleAnalyze}
          onReset={handleReset}
          isUploading={isUploading}
          analysisReady={analysisReady}
          documentSummaries={documentSummaries}
        />

        <SummaryPanel
          activeDocument={activeDocument}
          summary={summary}
          importantPoints={importantPoints}
          isAnalyzing={isUploading} 
          activeDocData={activeDocument && documentSummaries[activeDocument] ? documentSummaries[activeDocument] : null}
        />

        <ChatPanel 
          chatLog={chatLog} 
          onSendMessage={handleSendMessage} 
          activeDocument={activeDocument} 
          allDocuments={uploadedDocuments}
          isChatLoading={isChatLoading}
        />
      </main>
    </div>
  );
}